// apps/remote/src/App.jsx
import React from "react";
import ReactDOM from "react-dom";
import Header from "./components/Header";

import "./index.css";

const App = () => (
  <>
    <Header title="Header on remote" />
    <div className="container">
      <div>Name: remote</div>
      <div>Framework: react</div>
      <div>Language: JavaScript</div>
      <div>CSS: Empty CSS</div>
    </div>
  </>
);
ReactDOM.render(<App />, document.getElementById("app"));

// apps/article/src/App.vue
<script>
  import Header from './components/Header/Header.vue';

  export default {
    components: {
      Header,
    }
  }
</script>

<template>
  <div class="container">
    <Header />
    <main>
      <div>Framework: vue3</div>
      <div>Language: JavaScript</div>
      <div>CSS: Empty CSS</div>
    </main>
    <footer>Article Footer</footer>
  </div>
</template>

<style>
  .container {
    display: flex;
    flex-direction: column;
    justify-content: stretch;
  }
</style>
