// apps/react-example/src/App.jsx
import React from "react";
import { Route, Routes, BrowserRouter } from "react-router-dom";

import "./index.css";
import { Blog, Home } from "./pages";

export const App = ({ basePath }) => {
  console.log(basePath);
  return (
    <div className="container">
      <div>Hello in react example</div>
      <BrowserRouter basename={basePath}>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/blog" element={<Blog />} />
        </Routes>
      </BrowserRouter>
    </div>
  );
};

// apps/widget/src/App.svelte
<script>
  export let basePath = ''

  import {Router, Route} from 'svelte-routing'
  import Home from './pages/Home.svelte'
  import Blog from './pages/Blog.svelte'

  console.log('svelte', basePath)
</script>

<h1>Hello from Svelte example</h1>
<Router basepath={basePath}>
  <Route path="/" component={Home} />
  <Route path="blog" component={Blog} />

</Router>
